language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - DB=sqlalchemy

# command to run tests
script:
  - pytest --cov=api  --cov-report=xml

after_success:
  - python-codacy-coverage -r coverage.xml
notifications:
  email: false

